language: go

go:
- 1.8

env:
  - DEP_VERSION="0.4.1"

before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep

install:
 - go get -u golang.org/x/lint/golint
 - go get -u github.com/gordonklaus/ineffassign
 - dep ensure 

script:
- golint -set_exit_status ./censys/...
- ineffassign ./censys/

after_success:
  - bash <(curl -s https://codecov.io/bash) -f ./coverage.txt