
version: 1.0.{build}
image: Ubuntu1804
build:
  verbosity: minimal
deploy: off

clone_folder: c:\gopath\src\github.com\oucema001\censys-go
clone_depth: 1

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.10
  GOBIN: c:\gopath\bin

stack: go 1.10

install :
 - set PATH=%GOPATH%\bin;C:\gopath\bin;%PATH%
 - go version
 - go env
 - curl -L -o dep.exe https://github.com/golang/dep/releases/download/v0.4.1/dep-windows-amd64.exe
 - dep.exe ensure

test_script:
  - go test -v ./censys
